#Libraries

library(tidyr)
library(dplyr)
library(reshape) # rename from package:dyplyr is masked
library(ggplot2)
library(scales)
require(RColorBrewer)
require(gdata) #combine, first en last from package:dyplyr are masked
require(lubridate)
library(zoo)
library(chron)
library(xts) # first and last are masked from package:gdata en dplyr
library(gtable)
library(gridExtra)
library(maptools)
library(rgdal)
library(sp)
library(chron)
library(plyr)
library(gstat)
library(spacetime)
library(raster)
library(rgeos) 
library(magrittr)
library(gdistance)
library(leaflet)
library(readxl)
library(mgcv)
library(data.table)
library(plotly)
library(hrbrthemes)
library(ggpubr)
library(devtools)
library(httr)
library(jsonlite)
library(stringr)
library(purrr)
library(ranger)
library(TMB)
library(BBmisc)
library(lattice)
library(nlme)
library(lme4) #for mixed effect models
library(usdm)
library(pscl) # for zero-inflated poisson
library(MASS) #masks'select' from package:dplyr)
library(lmtest) #test whether ZIP or ZINB is better
library(margins)
library(tibble)
library(InformationValue)
library(arm)
library(WaveletComp)
library(oceanwaves)
library(DHARMa)
library(nnet)
detach("package:gridExtra", unload=TRUE)
library(splines)
options(stringsAsFactors = FALSE)
library(data.table) 
library(mgcv)
library(biglm)
library(fastDummies)
library(MuMIn)
library(suncalc)
library(leaps)
#library(equatiomatic)
library(lmerTest)
library(simr)
#library(speedglm)
#library(bigstep)
library(pracma)
library(iterators)
library(parallel)
library(foreach)
library(doParallel)
library(DescTools)